var a = {
    "msg": "查询成功",
    "data": {
        "perossList": [{
            "header": {
                "actualIncite": 2500.00,
                "adjustCase": "暂无说明",
                "adjustHeadId": 303,
                 "badge": "170612009", "budgetDesc": "暂无描述", "budgetIncite": 0, "budgetName": "网批", "contributionDegree": 50.00, "inciteDesc": "改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明", "inciteDescs": "改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明", "issueIncite": 5000.00, "phaseDisbursementAmount": 5000.00, "pouName": "温德威", "projectName": "测试项目0509", "projectTaskName": "测试项目0509-测试任务1", "referenceIncite": 2500.00, "reservedIncite": 0.00, "roleDesc": "负责IT侧项目任务的执行，达成任务目标，对项目具体分工和任务负责", "roleName": "IT组成员", "taskId": 36821, "taskName": "测试任务1", "unitName": "规划运营模块"
            }, "detail": [{ "actualIncite": 2500.00, "adjustCase": "暂无说明", "adjustHeadId": 303, "badge": "170706083", "budgetDesc": "暂无描述", "budgetIncite": 0, "budgetName": "网批", "contributionDegree": 50.00, "inciteDesc": "改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明", "inciteDescs": "改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明", "issueIncite": 5000.00, "phaseDisbursementAmount": 5000.00, "pouName": "王丹丹", "projectName": "测试项目0509", "projectTaskName": "测试项目0509-测试任务1", "referenceIncite": 2500.00, "reservedIncite": 0.00, "roleDesc": "负责IT侧项目任务的执行，达成任务目标，对项目具体分工和任务负责", "roleName": "IT组成员", "taskId": 36821, "taskName": "测试任务1", "unitName": "规划运营模块" }, { "actualIncite": 2500.00, "adjustCase": "暂无说明", "adjustHeadId": 303, "badge": "170612009", "budgetDesc": "暂无描述", "budgetIncite": 0, "budgetName": "网批", "contributionDegree": 50.00, "inciteDesc": "改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明", "inciteDescs": "改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明改激励说明", "issueIncite": 5000.00, "phaseDisbursementAmount": 5000.00, "pouName": "温德威", "projectName": "测试项目0509", "projectTaskName": "测试项目0509-测试任务1", "referenceIncite": 2500.00, "reservedIncite": 0.00, "roleDesc": "负责IT侧项目任务的执行，达成任务目标，对项目具体分工和任务负责", "roleName": "IT组成员", "taskId": 36821, "taskName": "测试任务1", "unitName": "规划运营模块" }]
        }, { "header": { "actualIncite": 1500.00, "adjustCase": "暂无说明", "adjustHeadId": 304, "badge": "170929046", "budgetDesc": "暂无描述", "budgetIncite": 0, "budgetName": "网批", "contributionDegree": 50.00, "inciteDesc": "22222222", "inciteDescs": "22222222", "issueIncite": 5000.00, "phaseDisbursementAmount": 3000.00, "pouName": "陈仕麟", "projectName": "测试项目0509", "projectTaskName": "测试项目0509-测试任务2", "referenceIncite": 1500.00, "reservedIncite": 2000.00, "roleDesc": "负责IT侧项目任务的执行，达成任务目标，对项目具体分工和任务负责", "roleName": "IT组成员", "taskId": 36822, "taskName": "测试任务2", "unitName": "规划运营模块" }, "detail": [{ "actualIncite": 1500.00, "adjustCase": "暂无说明", "adjustHeadId": 304, "badge": "171228036", "budgetDesc": "暂无描述", "budgetIncite": 0, "budgetName": "网批", "contributionDegree": 50.00, "inciteDesc": "22222222", "inciteDescs": "22222222", "issueIncite": 5000.00, "phaseDisbursementAmount": 3000.00, "pouName": "毛小俊", "projectName": "测试项目0509", "projectTaskName": "测试项目0509-测试任务2", "referenceIncite": 1500.00, "reservedIncite": 2000.00, "roleDesc": "负责项目总体目标的决策、风险控制和重大事项的协调，为项目责任人", "roleName": "项目总监", "taskId": 36822, "taskName": "测试任务2", "unitName": "N1" }, { "actualIncite": 1500.00, "adjustCase": "暂无说明", "adjustHeadId": 304, "badge": "170929046", "budgetDesc": "暂无描述", "budgetIncite": 0, "budgetName": "网批", "contributionDegree": 50.00, "inciteDesc": "22222222", "inciteDescs": "22222222", "issueIncite": 5000.00, "phaseDisbursementAmount": 3000.00, "pouName": "陈仕麟", "projectName": "测试项目0509", "projectTaskName": "测试项目0509-测试任务2", "referenceIncite": 1500.00, "reservedIncite": 2000.00, "roleDesc": "负责IT侧项目任务的执行，达成任务目标，对项目具体分工和任务负责", "roleName": "IT组成员", "taskId": 36822, "taskName": "测试任务2", "unitName": "规划运营模块" }] }], "formContentData": { "reservedIncites": 2000.00, "reservedTypeMeaning": "团队预留", "phaseDisbursementAmounts": 8000.00, "approveCode": "JLA0000000430", "year": 2018, "reservedType": "TEAM", "issueIncites": 10000.00, "inspireName": "2018激励预算-IT 1亿激励" }
    }, "count": 2, "status": "S"
}